spring.application.name=admin-web
spring.jmx.enabled=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.dynamic.datasource.master.url=jdbc:mysql://115.190.35.59:3306/archer-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true
spring.datasource.dynamic.datasource.master.username=root
spring.datasource.dynamic.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.root=debug
mybatis-plus.configuration.map-underscore-to-camel-case=true
server.servlet.context-path=/api
